SCALRCORE-24801 Integrations > Webhook update provider resource
Scalr/go-scalr pull request #105
Opened 2023-04-12 07:25 UTC by petroprotsakh

2023-04-12 09:30 UTC, DayS1eeper requested changes

2023-04-12 09:30 UTC, DayS1eeper commented on webhook_integration.go
> +	Events       []*EventDefinition `jsonapi:"relation,events,omitempty"`
All options have `omitempty`.
Can `Environments` be set to `[]` with update request`? Can `Timeout` be set to 0 or some default value?

2023-04-13 14:46 UTC, petroprotsakh commented on webhook_integration.go
> +	Events       []*EventDefinition `jsonapi:"relation,events,omitempty"`
@DayS1eeper Thanks, I forgot about the `omitempty` issue with to-many relations in jsonapi lib. Fixed.
For `Timeout` and other attributes it's ok, they're pointers with zero value of `nil`

2023-04-14 08:53 UTC, DayS1eeper commented on webhook_integration.go
> +	Events       []*EventDefinition `jsonapi:"relation,events,omitempty"`
@petroprotsakh 
>  For Timeout and other attributes it's ok, they're pointers with zero value of nil

https://pkg.go.dev/encoding/json#Marshal
> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.


With `omitempty` it is not possible to set `MaxAttempts=0` or `Timeout=0` or `Enabled=false` or `IsShared=false`.

2023-04-14 08:54 UTC, DayS1eeper commented on webhook_integration.go
> +	Events       []*EventDefinition `jsonapi:"relation,events,omitempty"`
Please add tests for updating from `IsShared=true` to `IsShared=false`, `MaxAttempts=3` to `MaxAttempts=0`.

2023-04-14 09:08 UTC, petroprotsakh commented on webhook_integration.go
> +	Events       []*EventDefinition `jsonapi:"relation,events,omitempty"`
@DayS1eeper https://github.com/Scalr/go-scalr/pull/105/files#diff-232db8d6b3359f96e57e7c98bfa6df3d2f05327ca7931898b372cd3c96375d65R122

2023-04-14 09:12 UTC, petroprotsakh commented on webhook_integration.go
> +	Events       []*EventDefinition `jsonapi:"relation,events,omitempty"`
@DayS1eeper 
>With omitempty it is not possible to set MaxAttempts=0 or Timeout=0 or Enabled=false or IsShared=false.

The type of `Timeout`, `IsShared`, etc is a pointer, not int/bool. Zero value for pointer is nil, when set to `0`/`false` it's no more zero.

2023-04-14 09:22 UTC, DayS1eeper approved these changes

2023-04-21 07:45 UTC, emocharnik commented
@petroprotsakh, Required builds are failing.

2023-04-21 08:00 UTC, emocharnik commented
@petroprotsakh, Required builds are failing.

2023-04-21 08:15 UTC, emocharnik commented
@petroprotsakh, Required builds are failing.

2023-04-21 08:45 UTC, emocharnik commented
@petroprotsakh, Required builds are failing.

2023-04-21 09:00 UTC, emocharnik commented
@petroprotsakh, Required builds are failing.

2023-04-21 09:15 UTC, emocharnik commented
@petroprotsakh, Some non-required builds are failing or stuck.

2023-04-21 09:30 UTC, merged