SCALRCORE-15690: IACP Provider > Multiscope variables
Scalr/go-scalr pull request #20
Opened 2021-02-08 09:29 UTC by vmotso

2021-02-09 15:07 UTC, vmotso commented on variable.go
> +	if options.QueryOptions != nil {
For variables, we need to include the query option for POST/PATCH.

2021-02-10 09:29 UTC, lbn requested changes

2021-02-10 09:29 UTC, lbn commented on variable_test.go
> +			// QueryOptions: &VariableCreateQueryOptions{Force: Bool(true)},
Need to test QueryOptions.

2021-02-12 09:22 UTC, lbn approved these changes

2021-02-15 15:30 UTC, merged