SCALRCORE-16315 TF Provider > Webhooks management
Scalr/go-scalr pull request #3
Opened 2020-07-31 19:32 UTC by mermoldy

2020-09-04 16:53 UTC, dmytrechko commented on endpoint.go
> +// IACP API docs: TODO
залишив, як є, поки що нема АПІ документації

2020-09-04 16:53 UTC, dmytrechko commented on endpoint.go
> +	Name        *string `jsonapi:"attr,name"`
забрав http-method із АПІ і звідси - лишня опція, лишні ресурси на підтримку, пропоную поки лише в моделі залишити.

2020-09-04 16:53 UTC, dmytrechko commented on endpoint.go
> +	Environment *Environment `jsonapi:"relation,environment,omitempty"`
забрав workspace relation, ми поки не підтримуємо endpoints на воркспейс скоупі

2020-09-04 16:53 UTC, dmytrechko commented on endpoint.go
> +func (o EndpointCreateOptions) valid() error {
тут лише додав валідацію на не пусті значення. 
Решту (URL, scope etc) - пропоную не додавати, ми таким чином лише собі роботи додамо. АПІ сервер повертає нормальні помилки, просто клієнт не вміє з ними працювати, пропоную саме це пофіксити в окремому тікеті

2020-09-04 16:53 UTC, dmytrechko commented on environment.go
> -	// List all the environments visible to the current user.
тут була копіпаста із go-tfe, залишив версію, яка була  у спайку

2020-09-04 16:53 UTC, dmytrechko commented on type_helpers.go
> -func AuthPolicy(v AuthPolicyType) *AuthPolicyType {
не юзалося, і самого типу нема (видалив із environment.go)

2020-09-04 16:53 UTC, dmytrechko commented on environment.go
> +type Organization struct {
додав новий тип, який повністю дублює Envrionment за винятком типу.
Стикнувся з наступним:
```Error: Error retrieving workspace existing_ws: Trying to Unmarshal an object of type "organizations", but "environments" does not match```
Судячи зі всього, коли міняли лінк в workspace.organization. із Organization  на Envrionment - тоді і поламалося.
Якщо я правильно розумію, go-scalr.Workspaces.ReadByID не працює.
Тому що наша АПІ повертає тип organizations
сс @lbn

2020-09-07 12:30 UTC, lbn requested changes

2020-09-07 12:30 UTC, lbn commented on endpoint.go
> +// IACP API docs: TODO
Can we make sure to remove this todo comment before merging?

2020-09-07 12:30 UTC, lbn commented on endpoint.go
> +	u := fmt.Sprintf("endpoints")
No need for a separate variable and string formatting. You can put `"endpoints"` straight into the `newRequest` call - https://github.com/Scalr/go-scalr/blob/develop/variable.go#L82

2020-09-07 12:30 UTC, lbn commented on endpoint.go
> +	u := fmt.Sprintf("endpoints")
Same here.

2020-09-07 12:30 UTC, lbn commented on environment.go
> +type Organization struct {
Discussed separately. This will have to stay.

2020-09-07 12:30 UTC, lbn commented on webhook.go
> +	u := fmt.Sprintf("webhooks")
Unnecessary sprintf and variable declaration.

2020-09-07 12:30 UTC, lbn commented on webhook.go
> +	u := fmt.Sprintf("webhooks")
Same here.

2020-09-07 21:16 UTC, dmytrechko commented on endpoint.go
> +// IACP API docs: TODO
I'll place the link to the whole section of IACP API Docs, and when they are  written, we'll just clarify the link,

2020-09-14 13:28 UTC, lbn approved these changes

2020-09-17 13:08 UTC, merged