SCALRCORE-18723 Fix Provider to handle 404 error
Scalr/go-scalr pull request #32
Opened 2021-08-12 13:41 UTC by ablik

2021-08-13 12:09 UTC, mermoldy requested changes

2021-08-13 12:09 UTC, mermoldy commented on scalr.go
> +		ErrResourceNotFound = result
@ablik did this code modify a global variable here? it looks like we doing something unnecessary

2021-08-13 12:26 UTC, ablik commented on scalr.go
> +	if r.StatusCode == 404 {
@mermoldy in this case we return only error code bit earlier:
https://github.com/Scalr/go-scalr/blob/4f18ffda54cba7d30913e6fc8d5e8cac2572665e/scalr.go#L435-L437
but I think it good point, we can return generic message in this case

2021-08-13 13:00 UTC, penja approved these changes

2021-08-13 13:00 UTC, penja commented on scalr.go
> +		ErrResourceNotFound = result
@ablik  Така штука поламає ерор хендлінг `ErrResourceNotFound = errors.New("resource not found")` спеціально створюється статичною щоб можна було перевірити.

2021-08-13 13:00 UTC, penja commented on scalr.go
> +		ErrResourceNotFound = result
сс @lbn

2021-08-13 13:00 UTC, penja requested changes
@lbn Pelase look into this one

2021-08-13 13:20 UTC, lbn requested changes

2021-08-13 13:20 UTC, lbn commented on scalr.go
> +	var result = fmt.Errorf(strings.Join(errs, "\n"))
[This would be a better way to add context to errors](https://blog.golang.org/go1.13-errors#TOC_3.).

You can create a new error struct that you can instantiate with a list of errors and implement the `Error() string` method that would stringify the error to something like `fmt.Sprintf("resource not found: %s", strings.Join(errs, "\n"))`. You will then need to change all `err == scalr.ErrResourceNotFound` references to `errors.Is(scalr.ErrResourceNotFound)` in the provider.

2021-08-18 11:34 UTC, mermoldy approved these changes

2021-08-25 08:53 UTC, penja commented on scalr.go
> +	Err     error
@ablik У коді я не бачу місця де встановлюється дана проперті значить у нас тут щось явно не так.

2021-08-25 13:25 UTC, ablik commented on scalr.go
> +	Err     error
@penja так воно тут зайве, планував використати для базовоi помилки, але зробив iнакше i забув випiляти

2021-08-25 13:26 UTC, penja commented on scalr.go
> +	Err     error
@ablik Я б його навпаки додав.

2021-08-25 13:35 UTC, ablik commented on scalr.go
> +	Err     error
@penja поки що не бачу юзкейсу, якщо створити в майбутньому специфiчнi помилки для конкретних типiв ресурсiв, його можна буде юзати для прокидання базовоi помилки щоб доступатись при розпаковцi. 
Але зараз в нас одна помилка i вiн виглядае зайвим

2021-08-25 13:39 UTC, penja commented on scalr.go
> +	Err     error
Через комон ерор буде зручно порівнювати.

2021-09-02 09:37 UTC, lbn approved these changes

2021-09-02 10:01 UTC, lbn approved these changes

2021-09-02 12:05 UTC, penja approved these changes

2021-09-06 10:57 UTC, merged