SCALRCORE-20287 TF Provider > scalr_role datasource: filter by name is broken
Scalr/go-scalr pull request #43
Opened 2021-09-24 14:45 UTC by petroprotsakh

2021-09-24 14:53 UTC, soltysss approved these changes

2021-09-27 07:18 UTC, penja commented on role.go
> +	Name    string  `url:"filter[role][name],omitempty"`
@petroprotsakh У нас кривий фільтр просочився у прев'ю профіль. `filter[role]` ок.

2021-09-27 07:22 UTC, penja commented on role.go
> +	Name    string  `url:"filter[role][name],omitempty"`
@maratkomarov @brezitskiy  Хоча щоб не було путанини серед девелоперів та юзерів що як фільтрувати я б усі фільтри звів до одного виду. `[object][atribute]` що думаєте?

2021-09-27 07:22 UTC, petroprotsakh commented on role.go
> +	Name    string  `url:"filter[role][name],omitempty"`
@penja `filter[role]` це фільтр по `id`, ні? Для атрибутів такий формат нормальний:
![image](https://user-images.githubusercontent.com/29977583/134862547-ef8fc419-f3d4-49d6-8011-d28cfe484dca.png)

2021-09-27 07:26 UTC, penja commented on role.go
> +	Name    string  `url:"filter[role][name],omitempty"`
@petroprotsakh Все що тобі попалось у пошуку криві фільтри. Згідно правиль філтрації ми обєкт фільтруємо по атрибутах `filter[attr_name]` а релейшини по `filter[relation_name][attribute]`. Глянь на флаг `is_atribute` у `FilterParameter`. Я пропоную випіляти даний флаг і всюди прийти до одного формату.

2021-09-27 07:29 UTC, penja commented on role.go
> +	Name    string  `url:"filter[role][name],omitempty"`
@petroprotsakh BTW фікс окей, це між іншим проблеми адже хто як хоче так і пише фільтри :), у нас має бути `There should be one-- and preferably only one --obvious way to do it.`

2021-09-27 23:58 UTC, maratkomarov requested changes
@penja @petroprotsakh куда делась дисскусия?

![image](https://user-images.githubusercontent.com/1004449/135000731-ca9f753a-2e14-4cdb-bb4a-c3302294ef83.png)

Конечно-же нужно поправить фильтр назад на `name` здесь в а API. 
BC хендлить не надо. Мы это зарелизили все неделю назад.

2021-09-28 00:05 UTC, maratkomarov commented
> Хоча щоб не було путанини серед девелоперів та юзерів що як фільтрувати я б усі фільтри звів до одного виду. [object][atribute] що думаєте?

@penja с удовольствием тебя бы поддержал, но это уже давно как правило которое каждый из нас должен фолловить https://github.com/Scalr/fatmouse/blob/master/docs/iacp-api.rst#filtering  Фильтры по полям должны фолловить структуру ресурса: `resource[field]`, `resource[relationship][field]` и тд. Все что написано не по стандарту нужно переделать

2021-09-28 11:26 UTC, petroprotsakh commented
Fix to be implemented on API side

2021-09-28 11:26 UTC, closed without merging