SCALRCORE-21436 Scalr Provider > Provider configuration resource and data source
Scalr/go-scalr pull request #64
Opened 2022-04-29 14:16 UTC by DayS1eeper

2022-05-03 08:36 UTC, brezitskiy approved these changes

2022-05-03 08:48 UTC, artemvang approved these changes

2022-05-04 08:38 UTC, penja commented on provider_configuration.go
> +	)
@DayS1eeper @brezitskiy Навішо там тут ці екшини? На мою думку не варто закладати бізнес лоігку у клієнт який має бути тупим як дверна ручка, це все варто перенести безпосередньо у провайдер.

2022-05-04 09:07 UTC, DayS1eeper commented on provider_configuration.go
> +	)
@penja I thought about it and decided to leave it here. These methods do not implement any business logic (as `syncArguments` from `terraform-provider-scalr` do). `CreateParameters` and `ChangeParameters` only parallelize requests execution.

> client is not right place for business logic
`Module.ReadBySource`, `Workspace.Read` - these methods implement business logic, they are not just a wrapper of API.

2022-05-09 08:25 UTC, penja requested changes

2022-05-09 08:25 UTC, penja commented on provider_configuration.go
> +	)
@DayS1eeper I still don't understand why we need this action with difference list of parameters why we don't create and use simple CRUD for  provider_configuration_paramters. It looks like ugly hack until our API has not support multiple request, I have not seen any advantages to add method like this into go clients. If you have question, let's discuss to with @brezitskiy

2022-05-09 08:25 UTC, penja commented on provider_configuration.go
> +	)
@DayS1eeper About parallelize requests execution, we can do this one also on terraform provider layer

2022-05-09 08:25 UTC, penja commented on provider_configuration.go
> +	GoogleCredentials     string `jsonapi:"attr,google-credentials"`
@DayS1eeper Why we don't add `omitempty` how is will work?

2022-05-09 08:25 UTC, penja commented on provider_configuration_link.go
> +	EnvironmentCreate(ctx context.Context, environmentID string, options ProviderConfigurationEnvironmentLinkCreateOptions) (*ProviderConfigurationLink, error)
@DayS1eeper @brezitskiy IMHO is a bad naming we don't create workspace, we link to workspace. Maybe is should be moved to workspace and environment modules???

2022-05-09 10:35 UTC, DayS1eeper commented on provider_configuration.go
> +	GoogleCredentials     string `jsonapi:"attr,google-credentials"`
@penja Because it does not affect anything.

2022-05-09 10:39 UTC, DayS1eeper commented on provider_configuration.go
> +	)
@penja moved this to provider

2022-05-09 11:12 UTC, penja approved these changes

2022-05-25 09:12 UTC, merged