SCALRCORE-16990 IACP API > Replace ingress-attributes with vcs-revisions
Scalr/go-scalr pull request #9
Opened 2020-10-05 11:02 UTC by penja

2020-10-05 12:57 UTC, mermoldy approved these changes

2020-10-07 07:24 UTC, penja commented on vcs_revision.go
> +	options := struct {
is typo thx @lbn

2020-10-07 07:25 UTC, lbn requested changes

2020-10-07 07:25 UTC, lbn commented on vcs_revision.go
> +	options := struct {
No includable in this resource.

2020-10-07 07:25 UTC, lbn commented on vcs_revision.go
> +	// Read reads a vcs revisions by its ID.
a VCS revision

2020-10-07 07:25 UTC, lbn commented on vcs_revision.go
> +// workspaces implements Workspaces.
Update please.

2020-10-07 07:25 UTC, lbn commented on vcs_revision.go
> +// Read a workspace by its name.
Update.

2020-10-15 14:55 UTC, lbn approved these changes

2020-10-21 15:12 UTC, merged