SCALRCORE-23827 Add id and name filters for all data sources
Scalr/go-scalr pull request #98
Opened 2023-03-30 12:33 UTC by denkl

2023-03-31 11:19 UTC, DayS1eeper requested changes

2023-03-31 11:19 UTC, DayS1eeper commented on tag.go
> +	ID      *string `url:"filter[tag],omitempty"`
Inconsistent naming.  `ProviderID` for `provider-configuration`
```
ProviderID   string `url:"provider-configuration,omitempty"`
```
but `ServiceAccount` for `service-account`
```
	ServiceAccount *string `url:"filter[service-account],omitempty"`
```
but `ID` for `tag`
```
	ID      *string `url:"filter[tag],omitempty"`
```

2023-04-03 06:53 UTC, denkl commented on tag.go
> +	ID      *string `url:"filter[tag],omitempty"`
Fixed.

2023-04-03 10:53 UTC, DayS1eeper approved these changes

2023-04-05 09:49 UTC, petroprotsakh approved these changes

2023-04-07 16:00 UTC, merged